<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dtx</string>
	</array>
	<key>name</key>
	<string>DTX (Documented LaTeX) [extended]</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\%&lt;\*readme&gt;.*\n$</string>
			<key>comment</key>
			<string>Readme</string>
			<key>contentName</key>
			<string>meta.embedded.block.content.macrocode.dtx</string>
			<key>end</key>
			<string>\%&lt;/readme&gt;</string>
			<key>name</key>
			<string>file.readme.dtx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.markdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\%&lt;\*lua&gt;</string>
			<key>comment</key>
			<string>Lua file</string>
			<key>end</key>
			<string>\%&lt;/lua&gt;</string>
			<key>name</key>
			<string>file.lua.dtx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\%    \\begin{macrocode}.*\n$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.line.macrocode.begin.dtx</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Macro code</string>
					<key>contentName</key>
					<string>meta.embedded.block.content.macrocode.dtx</string>
					<key>end</key>
					<string>\%    \\end{macrocode}.*\n$</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.line.macrocode.end.dtx</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.macrocode.dtx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.lua</string>
						</dict>
						<dict>
							<key>name</key>
							<string>luacode.dtx</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#commentBlockDtx</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\%    \\begin{macrocode}.*\n$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.line.macrocode.begin.dtx</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Macro code</string>
			<key>contentName</key>
			<string>meta.embedded.block.content.macrocode.dtx</string>
			<key>end</key>
			<string>\%    \\end{macrocode}.*\n$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.line.macrocode.end.dtx</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.macrocode.dtx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.latex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^%</string>
			<key>contentName</key>
			<string>comment.block.content.tex.dtx</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.block.tex.dtx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#shortVerbatim</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commentACaret</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.tex.dtx</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(%).*$\n?</string>
			<key>name</key>
			<string>comment.line.percentage.tex.dtx</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.tex.exlatex</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>commentACaret</key>
		<dict>
			<key>match</key>
			<string>\^\^A.*</string>
			<key>name</key>
			<string>comment.line.a.caret.dtx</string>
		</dict>
		<key>commentBlockDtx</key>
		<dict>
			<key>begin</key>
			<string>^%</string>
			<key>contentName</key>
			<string>comment.block.content.tex.dtx</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.block.tex.dtx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#shortVerbatim</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commentACaret</string>
				</dict>
			</array>
		</dict>
		<key>shortVerbatim</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.begin.short.verbatim.dtx</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.short.verabtim.dtx</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.end.short.verbatim.dtx</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\|)([^|]*)(\|)</string>
			<key>name</key>
			<string>markup.short.verbatim.dtx</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.tex.latex.dtx</string>
	<key>uuid</key>
	<string>97df4a50-4e1d-11e5-8302-eb6c379556cf</string>
</dict>
</plist>
