<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tex</string>
	</array>
	<key>firstLineMatch</key>
	<string>^%\!TEX program = (luatex|lualatex)</string>
	<key>name</key>
	<string>LuaTeX</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>((\\)(directlua|latelua|luadirect|luaexec)(\{))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.directlua.luatex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.luatex</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.directlua.begin.luatex</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Lua commands</string>
			<key>contentName</key>
			<string>support.function.lua.content.luatex</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.directlua.end.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>support.function.lua.luatex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.lua</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.lua.embedded.luatex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:\s*)((\\)begin)(\{)(luacode[*]?)(\})</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.be.latex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.latex</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.latex</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.latex</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.latex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>((\\)end)(\{)(\4)(\})(?:\s*\n)?</string>
			<key>name</key>
			<string>support.function.environment.general.luatex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.lua</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.lua.embedded.luatex</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tex.luatex</string>
	<key>uuid</key>
	<string>b1e4b1e2-4e1d-11e5-9e98-6b3ab1a77b4f</string>
</dict>
</plist>
