<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sty</string>
	</array>
	<key>name</key>
	<string>sty (LaTeX)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.tex.latex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tex.latex.sty</string>
	<key>uuid</key>
	<string>ec484c40-4e1d-11e5-8b82-7ba51ba46524</string>
</dict>
</plist>
