<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dtx</string>
	</array>
	<key>name</key>
	<string>dtx</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.tex.primitive.cs.family.box.tex</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Box family (TeX Primitive Control Sequences)</string>
			<key>match</key>
			<string>\\(badness|box|boxmaxdepth|cleaders|copy|dp|everyhbox|everyvbox|hbadness|hbox|hfuzz|hrule|ht|lastbox|leaders|overfullrule|prevdepth|setbox|unhbox|unhcopy|unvbox|unvcopy|vbadness|vbox|vfuzz|vrule|vtop|wd|xleaders)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.tex.primitive.cs.family.macro.tex</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Macro family (TeX Primitive Control Sequences)</string>
			<key>match</key>
			<string>\\(afterassignment|aftergroup|begingroup|csname|def|edef|endcsname|endgroup|expandafter|futurelet|gdef|global|globaldefs|let|long|noexpand|outer|relax|the|xdef)\b</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\%&lt;\*lua&gt;</string>
			<key>comment</key>
			<string>Lua file</string>
			<key>end</key>
			<string>\%&lt;/lua&gt;</string>
			<key>name</key>
			<string>file.lua.dtx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\%    \\begin{macrocode}.*$</string>
					<key>comment</key>
					<string>Macro code</string>
					<key>contentName</key>
					<string>content.macrocode.dtx</string>
					<key>end</key>
					<string>\%    \\end{macrocode}</string>
					<key>name</key>
					<string>macrocode.dtx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.lua</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>luacode.dtx</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.tex.latex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.dtx</string>
	<key>uuid</key>
	<string>634249ca-82b0-4971-9c82-c1a85e13c274</string>
</dict>
</plist>
