<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dtx</string>
	</array>
	<key>name</key>
	<string>dtx</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\%    \\begin{macrocode}</string>
			<key>comment</key>
			<string>Macro code</string>
			<key>end</key>
			<string>\%    \\end{macrocode}</string>
			<key>name</key>
			<string>macrocode.dtx</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.tex.latex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.dtx</string>
	<key>uuid</key>
	<string>634249ca-82b0-4971-9c82-c1a85e13c274</string>
</dict>
</plist>
