<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tex</string>
	</array>
	<key>name</key>
	<string>extended LaTeX</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?x)((\\)(?:(?:sub){0,2}section|(?:sub)?paragraph|chapter|part|addpart|addchap|addsec|minisec)(?:\*)?)(?:(\[)([^\[]*?)(\]))??(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.section.latex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.latex</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.optional.begin.latex</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.latex</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.optional.end.latex</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.latex</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>this works OK with all kinds of crazy stuff as long as section is one line</string>
			<key>contentName</key>
			<string>entity.name.section.latex</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.section.latex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.etex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.etex.elatex</string>
	<key>uuid</key>
	<string>634249ca-82b0-4971-9c82-c1a85e13c274</string>
</dict>
</plist>
